// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OMSWebMini.Model
{
    public partial class ProductsByCategory
    {
        public string CategoryName { get; set; }
        public int ProductsCount { get; set; }
    }
}