// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OMSWebMini.Model
{
    public partial class PurchasesByCustomer
    {
        public string CompanyName { get; set; }
        public decimal Purchases { get; set; }
    }
}