// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OMSWebMini.Model
{
    public partial class SalesByEmployee
    {
        public string LastName { get; set; }
        public decimal Sales { get; set; }
    }
}