// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OMSWebMini.Model
{
    public partial class Statistic
    {
        public long Id { get; set; }
        public string StatisticName { get; set; }
        public string Key { get; set; }
        public decimal? Value { get; set; }
    }
}