// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OMSWebMini.Model
{
    public partial class Summary
    {
        public int Id { get; set; }
        public decimal OverallSales { get; set; }
        public int OrdersQuantity { get; set; }
        public decimal MaxCheck { get; set; }
        public decimal MinCheck { get; set; }
        public decimal AverageCheck { get; set; }
    }
}